- Dockerfile
- Jenkinsfile
- configuracoes/default.conf
- docker/startup.sh
[AB#94547](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/94547)
> Add CI/CD + Dockerfile + Nginx conf

- src/components/cdep/erro-geral-login/index.tsx
- src/components/cdep/erro-geral-login/style.ts
- src/core/constats/mensagens.ts
- src/core/dto/retorno-base-dto.ts
- src/pages/criar-conta/index.tsx
- src/pages/login/index.tsx
[AB#97283](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97283)
> Login e Cadastro - tratar  erros com retorno base dto

- src/pages/criar-conta/index.tsx
- src/pages/login/index.tsx
[AB#97283](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/97283)
> Login e Cadastro - limitar tamanho dos campos

- src/components/cdep/cadastros/auxiliares/config/index.tsx
- src/components/cdep/cadastros/auxiliares/form/index.tsx
- src/components/lib/sider/index.tsx
- src/core/constants/inputs-cadastros.ts
- src/core/constants/mensagens.ts
AB#94006
Criado validações de campos de edição
> Criado validações de campos de edição

- src/pages/cadastros/acervo/list/index.tsx
> FIX 104681 - Lista de Acervo - quebrar palavra na coluna título

- src/pages/cadastros/acervo/form/form-fields/select-suporte.tsx
> Adicionando tipo ao suporte em artes gráficas

- src/pages/cadastros/acervo/form/form-fields/input-tombo.tsx
> Ajustando o campo para 12

- src/pages/cadastros/acervo/form/form-fields/editor-descricao.tsx
- src/pages/cadastros/acervo/form/form-fields/input-disponibilizacao.tsx
- src/pages/cadastros/acervo/form/form-fields/input-duracao.tsx
> Corrigindo nome dos campos

- src/pages/consulta-acervo/index.tsx
> FIX 109740 - Ajuste na paginação na de consulta de acervo

- src/core/dto/form-cadastro-acervo.ts
- src/pages/cadastros/acervo/form/index.tsx
> Fix/111851 -> release

- src/pages/consulta-acervo/detalhes/detalhes-acervo-area-publica.tsx
- src/pages/consulta-acervo/detalhes/index.tsx
> fix112033 - Detalhamento da descrição dos acervos - ajustes em espaçamento

- src/components/cdep/perfis/index.tsx
> fix/112586 -> release

- src/pages/cadastros/acervo/form/index.tsx
> fix - 112608 Campos dimensões enviar no endpoint o valor formatado

- src/pages/inicial/index.tsx
> 113580 - insercao de campos tipo de acervo e titulo

- src/core/enum/tipo-usuario-enum.ts
- src/pages/operacoes/solicitacao/components/card-dados-solicitante/index.tsx
> fix 113504 - Dados Solicitante - add descrição do tipo de usuário

- src/pages/cadastros/acervo/form/form-fields-config/audiovisual.ts
> 1) FRONT - No cadastro do acervo Audiovisual o campo cópia deve vir abaixo de suporte e antes da duração

- src/core/dto/form-cadastro-acervo.ts
- src/pages/cadastros/acervo/utils/index.tsx
> fix 114223 - Considerar acessoDocumentosIds sendo array

- src/core/dto/dados-solicitante-dto.ts
- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
- src/pages/cadastros/atendimento-solicitacoes/list/index.tsx
> Correções de ajustes pós revisão de critérios

- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
- src/pages/cadastros/atendimento-solicitacoes/solicitacao-manual/index.tsx
> Fix/115431 -> release

- src/components/lib/sider/styles.ts
> corrigira cor dos menus

- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
> fix/115602 - ajustando permissao dos botoes de acao para perfil so consulta

- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
[AB#115652](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115652)
> fix/115652 - ajustara o initialValue do date picker quando nao tiver data

- src/core/styles/colors.ts
- src/pages/consulta-acervo/filtro-consulta-acervo/index.tsx
> fix/115653 - ajustara campos ano inicial e final para aceitar o range de 1900 a 2099 e limpar caracteres especiais

- src/pages/consulta-acervo/filtro-consulta-acervo/index.tsx
> fix/115653 - mudara mensagem de erro dos campos de ano inicial e final

- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
> fix/115677 - ajustara as regras pra desabilitar o botao de finalizar e cancelar atendimento

- src/core/constants/mensagens.ts
- src/pages/cadastros/atendimento-solicitacoes/form/index.tsx
> fix/115674 - mudara mensagem do cancelar item do atendimento

- src/core/enum/permissao-enum.ts
> alteracao nos valores das permissoes da gestao de visita calendario

- src/core/dto/acervo-solicitacao-detalhe-dto.ts
- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> Fix/115748 - removera hora da data de solicitacao

- src/pages/operacoes/solicitacao/components/lista-acervos-solicitacao/index.tsx
> Fix/116416 - removera o horario da data de visita

- src/pages/operacoes/solicitacao/components/btn-enviar-solicitacao/index.tsx
- src/pages/operacoes/solicitacao/components/lista-acervos-solicitacao/index.tsx
[AB#116454](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116454)
> Retornando a tela inicial

- src/components/cdep/perfis/index.tsx
[AB#116388](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116388)
> Trocando a etiqueta de RF para LOGIN

- src/pages/operacoes/solicitacao/components/btn-enviar-solicitacao/index.tsx
[AB#116483](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116483)
> Ajustando o nome do botão cancelar

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> 116487 - Situacao 6 - ajuste permissao do botao finalizar

- src/pages/gestao/calendario/mes/detalhes-evento-dia/index.tsx
> 116487 - Situacao 3 - ajuste permissao exluir suspensao

- src/pages/gestao/calendario/mes/index.tsx
> deixando somente uma tag caso tenha mais de uma

- src/pages/gestao/calendario/mes/detalhes-evento-dia/index.tsx
> ajustando limite de caracteres do modal de justificativa da suspensao

- src/core/dto/acervo-solicitacao-confirmar-dto.ts
- src/core/dto/acervo-solicitacao-detalhe-dto.ts
- src/core/dto/acervo-solicitacao-item-detalhe-resumido-dto.ts
- src/core/enum/situacao-atendimento-enum.ts
- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
[AB#115820](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/115820)
[AB#116848](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/116848)
> FRONT - Story/115820 --> RELEASE

- src/core/dto/acervo-solicitacao-item-detalhe-resumido-dto.ts
- src/core/dto/acervo-solicitacao-manual-dto.ts
- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/index.tsx
> Story/110575 -> dev

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/components/modal-adicionar-acervo/index.tsx
> Fix/117784 -> release

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> fix/117587 - ajustara o desabilitar do campo data visita quando situacao cancelada

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> fix/117784 - ajustara o range das datas

- src/components/cdep/input/instituicao/index.tsx
> fix/118294 - ajustara mensagem de erro

- src/core/enum/tipo-perfil-enum.ts
- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> fix/118325 - ajustara validacao do botao cancelar atendimento e removido o botao finalizar

- src/components/cdep/destacar-texto/index.tsx
- src/pages/consulta-acervo/lista-cards-consulta-acervo/index.tsx
> fix/118296 - ajustara a funcao de destacar palavra

- src/pages/operacoes/atendimento-solicitacoes/form/components/modal-atendimento/index.tsx
> fix/118409 - adicionara obrigatoriedade no campo data visita

- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/index.tsx
> ajustara estado do botao confirmar

- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/index.tsx
> fix/118408 - ajustara o estado do botao confirmar

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> fix/118506 - nova regra pra desabilitar o botao editar

- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/index.tsx
> fix/118408 - ajustara chamada de endpoint

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> fix/118529 - ajuste validacao dos botoes

- src/pages/operacoes/atendimento-solicitacoes/form/components/modal-atendimento/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/components/modal-adicionar-acervo/index.tsx
> fix/118529 - ajuste utc data

- src/core/dto/acervo-solicitacao-item-retorno-dto.ts
- src/pages/consulta-acervo/components/button-enviar-para-minha-selecao/index.tsx
- src/pages/consulta-acervo/components/selecionar-acervo/index.tsx
- src/pages/operacoes/solicitacao/components/btn-cancelar-solicitacao/index.tsx
- src/pages/operacoes/solicitacao/components/lista-acervos-solicitacao/index.tsx
- src/pages/operacoes/solicitacao/index.tsx
> fix 119082 -  Erro ao cancelar atendimento com acervo indisponível

- src/core/dto/form-cadastro-acervo.ts
- src/pages/cadastros/acervo/form/form-fields/input-localizacao-pha.tsx
> Removendo a obrigatoriedade do campo localização pha

- src/pages/consulta-acervo/filtro-consulta-acervo/index.tsx
> Sistema está permitindo que o ano inicial seja maior que o ano final

- src/pages/cadastros/acervo/form/form-fields/input-dimensao-altura.tsx
- src/pages/cadastros/acervo/form/form-fields/input-dimensao-diametro.tsx
- src/pages/cadastros/acervo/form/form-fields/input-dimensao-largura.tsx
- src/pages/cadastros/acervo/form/form-fields/input-dimensao-profundidade .tsx
> Aumentando o tamanho das dimensões

- src/pages/cadastros/acervo/form/form-fields/input-edicao.tsx
> Aumentando o tamanho do campo Edição para 30 caracteres

- src/core/services/acervo-solicitacao-service.ts
- src/pages/operacoes/solicitacao/components/lista-acervos-solicitacao/index.tsx
> Fix/119108 -> preprod

- src/pages/operacoes/atendimento-solicitacoes/form/components/modal-atendimento/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/components/modal-adicionar-acervo/index.tsx
> Fix/118843 -> preprod

- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/components/modal-adicionar-acervo/index.tsx
> Fix/120065 -> preprod

- package.json
- src/pages/consulta-acervo/components/text-content-card/index.tsx
- src/pages/consulta-acervo/detalhes/detalhes-acervo-area-publica.tsx
- yarn.lock
> Fix/119597 -> preprod

- src/pages/cadastros/acervo/importar-acervo/index.tsx
> fix/119714 - Ajustara cor da barra de progresso

- src/pages/cadastros/acervo/importar-acervo/index.tsx
> fix/119714 - Substituira barra de progresso por tag e renomeara o botao atualizar

- src/pages/cadastros/acervo/importar-acervo/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/form/components/modal-atendimento/index.tsx
> Preprod -> master

- src/pages/consulta-acervo/components/text-content-card/index.tsx
- src/pages/consulta-acervo/detalhes/detalhes-acervo-area-publica.tsx
> Função por arrow function e ajuste de tipagem

- src/pages/operacoes/solicitacao/components/lista-acervos-solicitacao/index.tsx
> 123156 - Ajuste formato data de visita solicitante

- src/core/dto/acervo-emprestimo-prorrogacao-dto.ts
- src/pages/operacoes/atendimento-solicitacoes/form/components/modal-atendimento/index.tsx
> 122223 - Obrigatoriedade data prorrogação de devolução

- src/pages/operacoes/atendimento-solicitacoes/list/index.tsx
> 122377 - Ajuste tipo de campo numerico

- src/components/cdep/input/date/index.tsx
- src/pages/operacoes/atendimento-solicitacoes/solicitacao-manual/components/modal-adicionar-acervo/index.tsx
> 122359 - Ajuste novo componente data para DatePicker

- src/pages/consulta-acervo/provider/index.tsx
> 122222 - Ajuste roteamento consulta acervo ao detalhar e limpar busca

- src/pages/operacoes/atendimento-solicitacoes/form/index.tsx
> 121491 - Ajuste scroll x em grid de solicitações de atendimento

- src/components/cdep/sider/menus/lista-menus/menu-relatorios.tsx
- src/core/enum/field-acervo-enum.ts
- src/core/enum/menu-enum.ts
- src/core/enum/routes.ts
- src/core/services/relatorios-service.ts
- src/pages/relatorios/devolucao-livros/index.tsx
- src/routes/index.tsx
Apresenta um novo item de menu para "Controle de Devoluções de Livros" na seção de relatórios, incluindo seus valores de enumeração e rota. As permissões para este item de menu são definidas com base nas funções do CadastroCrédito.
> Relatório Controle de Devoluções de Livros
